# Site settings
title:       txtr
email:       somostexter@gmail.com
author:      Esto es Texter
description: "No leas mañana lo que puedes leer hoy. Somos un archivador de historias extraordinarias escritas por gente común."
baseurl:     ""
url:         "https://www.texter.cl/"
date_format: "%b %-d, %Y"
header_pages:
 - about.md
 - contact.html

google_analytics:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true

# Preview image for social media aka og:image and twitter:image
post_preview_image: true

# Disqus post comments
disqus_shortname:

# Social icons
facebook_username: Textercl
twitter_username: TexterCl
linkedin_username: TexterCl
instagram_username: TexterCl


# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false

text:
  pagination:
    newer: 'avanza'
    older: 'retrocede'
  share_buttons:
    text:         'Compártelo en:'
    facebook:     'Compártelo en Facebook'
    twitter:      'Compártelo en Twitter'


  post:
    updated:        'Subido'
    minute_read:    'Minutos de lectura'
    related_posts:  'Te puede interesar'
    post_footer:    'Lorem ipsum'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    :title
paginate:     5
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
